-- Create budget_rollovers table
create table if not exists budget_rollovers (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category_id bigint references categories(id) on delete cascade not null,
  month int not null,
  year int not null,
  amount numeric not null default 0,
  unique (category_id, month, year)
);

-- Note: Ensure this refers to the 0-indexed JS month, or 1-indexed. The implementation will use JS month (0-11).
