-- Create Fuel Logs Table
create table fuel_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  vehicle_type text not null,
  fuel_type text not null check (fuel_type in ('Pertalite', 'Pertamax', 'Pertamax Turbo', 'Solar', 'Dexlite')),
  initial_km numeric not null,
  final_km numeric not null,
  distance numeric generated always as (final_km - initial_km) stored,
  price_per_liter numeric not null,
  liters numeric not null,
  total_cost numeric generated always as (price_per_liter * liters) stored,
  date date not null default current_date
);

-- Enable Row Level Security
alter table fuel_logs enable row level security;

-- Create Policy for Select
create policy "Enable read access for all users" on fuel_logs
  for select using (true);

-- Create Policy for Insert
create policy "Enable insert access for all users" on fuel_logs
  for insert with check (true);

-- Create Policy for Update
create policy "Enable update access for all users" on fuel_logs
  for update using (true);

-- Create Policy for Delete
create policy "Enable delete access for all users" on fuel_logs
  for delete using (true);
