-- Create Wallets Table
create table wallets (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null check (type in ('cash', 'ewallet', 'investment', 'bank')),
  balance numeric default 0,
  icon text
);

-- Create Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  type text not null check (type in ('income', 'expense')),
  budget_limit numeric default 0, -- Pagu Anggaran
  icon text
);

-- Create Transactions Table
create table transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  date date not null default current_date,
  amount numeric not null,
  description text,
  category_id bigint references categories(id),
  wallet_id bigint references wallets(id),
  type text not null check (type in ('income', 'expense'))
);

-- Insert Default Categories
insert into categories (name, type, icon, budget_limit) values
('Gaji', 'income', 'MdAttachMoney', 0),
('Bonus', 'income', 'MdCardGiftcard', 0),
('Makan & Minum', 'expense', 'MdRestaurant', 2000000),
('Transportasi', 'expense', 'MdDirectionsCar', 500000),
('Belanja', 'expense', 'MdShoppingCart', 1000000),
('Tagihan', 'expense', 'MdReceipt', 1500000),
('Hiburan', 'expense', 'MdMovie', 500000),
('Kesehatan', 'expense', 'MdLocalHospital', 500000);

-- Insert Default Wallets
insert into wallets (name, type, balance, icon) values
('Dompet Tunai', 'cash', 500000, 'MdMoney'),
('BCA', 'bank', 5000000, 'MdAccountBalance'),
('GoPay', 'ewallet', 250000, 'MdPhoneAndroid'),
('Bibit', 'investment', 10000000, 'MdTrendingUp');
